//List of spritemaps (might use only one in the final version) | used in: rendering
const sprite = {
  enemy_cube: new Image(),
  enemy_looterCube: new Image(),
  enemy_largeCube: new Image(),
  enemy_icosphere: new Image(),
  enemy_mail: new Image(),
  enemy_star: new Image(),
  enemy_starPiece: new Image(),
  enemy_miniArrow: new Image(),
  enemy_corruptedCloud: new Image(),
  enemy_carrier: new Image(),
  enemy_carrierTurret: new Image(),
  player_scout: new Image(),
  player_companion: new Image(),
  projectile_ROCKET: new Image(),
  projectile_BASIC: new Image(),
  projectile_CHAKRAM: new Image(),
  projectile_NEON: new Image(),
  projectile_enemyBASIC: new Image(),
  projectile_enemyCLOUD: new Image(),
  projectile_SPREAD: new Image(),
  projectile_spreadProjectile: new Image(),
  projectile_explosion: new Image(),
  UI_cursorFire: new Image(),
  UI_cursorNoFire: new Image(),
  UI_HPpanel: new Image(),
  UI_durationPanel: new Image(),
  UI_motherboard: new Image(),
  UI_motherboardRay: new Image(),
  UI_motherboardAngela: new Image(),
  UI_motherboardMap: new Image(),
  UI_motherboardFan: new Image(),
  UI_motherboardGPUFan: new Image(),
  UI_visibility: new Image(),
  UI_warning: new Image(),
  UI_chase: new Image(),
  UI_ignore: new Image(),
  UI_spawn: new Image(),
  UI_loot: new Image(),
  UI_drop: new Image(),
};

const DialogueData = {
  level_0: {
    text: [
      "Placeholder text 0",
      "Placeholder text 1",
      "Placeholder text instant 3",
      "Placeholder text 4",
    ],
    color: ["yellow", "yellow", "white", "white"],
    triggerType: ["timer", "after", "after", "after"], //timer - level timer, wave - start of a wave, after - goes right after a specific dialogue index
    triggerIndex: [240, 0, 1, 2],
    ttl: [400, 1, 400, 400], //ttl - time to stay on the screen after typing is done
  },
  level_1: {
    text: ["Placeholder text 0", "Placeholder text 1", "Placeholder text 2"],
    color: ["yellow", "white", "white"],
    triggerType: ["timer", "after", "after"], //timer - level timer, wave - start of a wave, after - goes right after a specific dialogue index
    triggerIndex: [240, 0, 1],
    ttl: [400, 400, 400],
  },
};

//Default database for ingame weapons | used in: first inicialization
const WeaponData = {
  BASIC: {
    index: 0,
    sprite: sprite.projectile_BASIC,
    name: "BASIC",
    animation: false,
    rotationAnimation: false,
    bullets: 1,
    damage: 3,
    speed: 15,
    width: 5,
    height: 50,
    cooldown: 200,
    duration: 0,
    status: "DEFAULT",
  },
  DOUBLE: {
    index: 1,
    sprite: sprite.projectile_BASIC,
    name: "DOUBLE",
    animation: false,
    rotationAnimation: false,
    bullets: 2,
    damage: 3,
    speed: 15,
    width: 5,
    height: 50,
    cooldown: 150,
    duration: 600,
    status: "LOCKED",
  },
  SPRAY: {
    index: 2,
    sprite: sprite.projectile_BASIC,
    name: "SPRAY",
    animation: false,
    rotationAnimation: false,
    bullets: 3,
    damage: 3,
    speed: 15,
    width: 5,
    height: 50,
    cooldown: 150,
    duration: 600,
    status: "LOCKED",
  },
  ROCKET: {
    index: 3,
    sprite: sprite.projectile_ROCKET,
    name: "ROCKET",
    animation: false,
    rotationAnimation: false,
    bullets: 1,
    damage: 5,
    speed: 7,
    width: 12,
    height: 33,
    cooldown: 300,
    duration: 600,
    status: "LOCKED",
  },
  SPREADER: {
    index: 4,
    sprite: sprite.projectile_SPREADER,
    name: "SPREADER",
    animation: false,
    rotationAnimation: false,
    bullets: 1,
    damage: 2,
    speed: 8,
    width: 14,
    height: 30,
    cooldown: 300,
    duration: 600,
    piercing: false,
    status: "LOCKED",
  },
  SPREADER_PROJECTILE: {
    index: 99,
    sprite: sprite.projectile_spreadProjectile,
    name: "SPREADER_PROJECTILE",
    animation: false,
    rotationAnimation: false,
    bullets: 1,
    damage: 2,
    speed: 15,
    width: 7,
    height: 13,
    piercing: false,
    status: "UNAVAILABLE",
  },
  LASER: {
    index: 5,
    name: "LASER",
    animation: false,
    rotationAnimation: false,
    bullets: 1,
    damage: 1,
    speed: 0,
    width: 1,
    height: 1,
    cooldown: 1,
    duration: 600,
    piercing: true,
    hitCD: 200,
    color: "#B2B5FF",
    status: "LOCKED",
  },
  CHAKRAM: {
    index: 6,
    sprite: sprite.projectile_CHAKRAM,
    name: "CHAKRAM",
    animation: false,
    rotationAnimation: true,
    rotationSpeed: 20,
    bullets: 1,
    damage: 2,
    speed: 10,
    width: 70,
    height: 70,
    cooldown: 300,
    duration: 600,
    piercing: true,
    hitCD: 200,
    status: "LOCKED",
  },
  NEONTHROWER: {
    index: 7,
    sprite: sprite.projectile_NEON,
    name: "NEONTHROWER",
    animation: false,
    rotationAnimation: true,
    rotationSpeed: 10,
    bullets: 1,
    damage: 4,
    speed: 7,
    width: 50,
    height: 50,
    cooldown: 25,
    duration: 600,
    piercing: true,
    hitCD: 200,
    status: "LOCKED",
  },
};

class DefaultSetup {
  constructor() {
    this.name = "SCOUT";
    this.speed = 12;
    this.width = 75;
    this.height = 75;
    this.widthOnPic = 150;
    this.heightOnPic = 150;
    this.weaponDuration = 0;
    this.maxShield = [100, 50];
    this.maxHP = [100, 50];
    this.level = 0;
    this.companions = 0;
    this.musicMultiplier = 5;
    this.soundMultiplier = 5;
  }
}

/*
ENEMY IDEAS:
  ball
  cell
*/

const EnemyData = {
  cube: {
    type: "cube",
    chaseDistance: Infinity,
    behaviour: "chase",
    sprite: sprite.enemy_cube,
    rotation: true,
    widthOnPic: 75,
    heightOnPic: 75,
    attackCDvalue: 2000,
    bulletType: "BASIC",
    collisionDamage: 10,
    width: 60,
    height: 60,
    speed: 5,
    defaultSpeed: 5,
    HP: 6,
    maxHP: 6,
    animation: true,
    animationFrames: 5,
    animationFPS: 12,
    deathAnimationFPS: 3,
    deathAnimationFrames: 9,
  },
  looterCube: {
    type: "looterCube",
    chaseDistance: Infinity,
    behaviour: "loot",
    sprite: sprite.enemy_looterCube,
    rotation: true,
    widthOnPic: 75,
    heightOnPic: 75,
    attackCDvalue: 2000,
    bulletType: "BASIC",
    collisionDamage: 10,
    randomDrop: true,
    width: 60,
    height: 60,
    speed: 10,
    defaultSpeed: 10,
    HP: 6,
    maxHP: 6,
    animation: true,
    animationFrames: 5,
    animationFPS: 12,
    deathAnimationFPS: 3,
    deathAnimationFrames: 9,
  },
  icosphere: {
    type: "icosphere",
    chaseDistance: Infinity,
    behaviour: "chase",
    sprite: sprite.enemy_icosphere,
    rotation: true,
    widthOnPic: 85,
    heightOnPic: 85,
    attackCDvalue: 2000,
    bulletType: "BASIC",
    collisionDamage: 10,
    width: 85,
    height: 85,
    speed: 5,
    defaultSpeed: 5,
    HP: 8,
    maxHP: 8,
    animation: true,
    animationFrames: 7,
    animationFPS: 12,
    deathAnimationFPS: 6,
    deathAnimationFrames: 5,
  },
  mail: {
    type: "mail",
    behaviour: "spawn",
    sprite: sprite.enemy_mail,
    rotation: false,
    widthOnPic: 90,
    heightOnPic: 90,
    attackCDvalue: 5000,
    bulletType: "miniArrow",
    collisionDamage: 10,
    width: 90,
    height: 90,
    speed: 3,
    defaultSpeed: 3,
    HP: 12,
    maxHP: 12,
    animation: false,
    spawnAnimationFrames: 5,
    spawnAnimationFPS: 6,
    spawnAnimationIndex: 0,
    deathAnimationFPS: 6,
    deathAnimationFrames: 6,
  },
  miniArrow: {
    type: "miniArrow",
    behaviour: "chase",
    sprite: sprite.enemy_miniArrow,
    rotation: true,
    widthOnPic: 40,
    heightOnPic: 40,
    attackCDvalue: 2000,
    bulletType: "MINIBASIC",
    collisionDamage: 10,
    width: 40,
    height: 40,
    speed: 5,
    defaultSpeed: 5,
    HP: 3,
    maxHP: 3,
    animation: true,
    animationFrames: 6,
    animationFPS: 10,
    deathAnimationFPS: 6,
    deathAnimationFrames: 4,
  },
  largeCube: {
    type: "largeCube",
    behaviour: "ignore",
    sprite: sprite.enemy_largeCube,
    rotation: true,
    cache: ["cube", 3],
    widthOnPic: 150,
    heightOnPic: 150,
    attackCDvalue: 2000,
    bulletType: "BASIC",
    collisionDamage: 10,
    width: 150,
    height: 150,
    speed: 2,
    defaultSpeed: 2,
    HP: 10,
    maxHP: 10,
    animation: true,
    animationFrames: 5,
    animationFPS: 12,
    deathAnimationFPS: 3,
    deathAnimationFrames: 9,
  },
  star: {
    type: "star",
    behaviour: "spawn",
    sprite: sprite.enemy_star,
    rotation: false,
    widthOnPic: 120,
    heightOnPic: 120,
    attackCDvalue: 5000,
    bulletType: "starPiece",
    collisionDamage: 25,
    width: 120,
    height: 120,
    speed: 3,
    defaultSpeed: 3,
    HP: 10,
    maxHP: 10,
    animation: true,
    animationFrames: 4,
    animationFPS: 6,
    deathAnimationFPS: 8,
    deathAnimationFrames: 4,
  },
  starPiece: {
    type: "starPiece",
    behaviour: "collide",
    collisionDamage: 20,
    sprite: sprite.enemy_starPiece,
    rotation: true,
    widthOnPic: 40,
    heightOnPic: 40,
    width: 40,
    height: 40,
    speed: 4,
    defaultSpeed: 4,
    HP: 1,
    maxHP: 1,
    animation: false,
  },
  corruptedCloud: {
    type: "corruptedCloud",
    behaviour: "chase",
    bulletType: "CLOUD",
    attackCDvalue: 50,
    collisionDamage: 20,
    sprite: sprite.enemy_corruptedCloud,
    rotation: false,
    widthOnPic: 120,
    heightOnPic: 120,
    width: 120,
    height: 120,
    speed: 2,
    defaultSpeed: 2,
    HP: 50,
    maxHP: 50,
    animation: true,
    animationFrames: 4,
    animationFPS: 6,
    deathAnimationFPS: 8,
    deathAnimationFrames: 4,
  },
  carrier: {
    type: "carrier",
    behaviour: "ignore",
    bulletType: "BASIC",
    turrets: 4,
    turretDist: [35, 80, 35, 80],
    turretAngle: [0, 0, 0, 0],
    turretWidthOnPic: 40,
    turretHeightOnPic: 40,
    attackCDvalue: 2000,
    collisionDamage: 20,
    sprite: sprite.enemy_carrier,
    rotation: true,
    turretSprite: sprite.enemy_carrierTurret,
    widthOnPic: 100,
    heightOnPic: 200,
    width: 100,
    height: 200,
    speed: 1,
    defaultSpeed: 1,
    HP: 50,
    maxHP: 50,
    animation: false,
    deathAnimationFPS: 8,
    deathAnimationFrames: 5,
  },
};
